name: Advancedcobblegenerator
version: '${project.version}'
main: de.tomstahlberg.advancedcobblegenerator.advancedcobblegenerator.Main
api-version: 1.19
depend: [Vault]
softdepend: [Essentials, ServerSystem, IridiumSkyblock]
commands:
  advancedcobblegenerator:
    description: 'command for reloading purposes'
    aliases: [advancedcobbler, acg, cobblegen, cobbler, cobble, ores, oregen, oresgen]